In [2]:
# 1D array
a=np.array([1,4,3,6])
a


array([1, 4, 3, 6])

In [4]:
# 2x3 array of zeros
b=np.zeros((2,3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
# 1D array of ones
c = np.ones((3,))
c


array([1., 1., 1.])

In [6]:
 # [0, 2, 4, 6, 8]
d = np.arange(0, 10, 2)
d

array([0, 2, 4, 6, 8])

In [10]:
# Math operations
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])
sum_ = x + y
sum_


array([11, 22, 33])

In [8]:
prod = x * y
prod


array([10, 40, 90])

array([0.        , 0.69314718, 1.09861229])

In [12]:
# Statistics

array([ 5, 10, 15])

In [13]:
mean = np.mean(data)
mean

np.float64(10.0)

In [14]:
std = np.std(data)
std

np.float64(4.08248290463863)

In [15]:
median = np.median(data)
median

np.float64(10.0)